# -*- coding: utf-8 -*-
"""WeightConverter.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12p-brkc2l_Pm_MCKApPbHISMouUoN3Cx
"""

weight = int(input("Enter Weight: "))
unit = input("Lbs or Kg? : ")
if unit.upper() == "L":
  converted = weight*0.45
  print(f"You are {converted} kilos")
else:
  converted = weight/0.45  
  print(f"You are {converted} pound")

